### ISSUE TITLE
大神牛逼，不知道windows下有人搞没有

### ISSUE THREAD

**Issue by 519984307** [kedixa/coke#19]

**Comment by kedixa** [comment]
这个项目仅依赖 [sogou/workflow](https://github.com/sogou/workflow)，要适配Windows应该不需要太大的改动，但目前作者没有现成的Windows开发环境，且业余时间主要用来做功能开发，适配Windows估计要在较晚的时候进行。

如果想玩玩，Windows Subsystem for Linux下应该可以直接跑这个项目。

现有的支持windows的C++协程项目在github里有很多，其中一些项目的思路是给某个event库套个壳，或者自己写个event库套个壳。本项目其实也是workflow套壳，但workflow除了核心的异步事件机制外，还有完备的http/redis/mysql/dns等协议解析、服务治理、负载均衡等诸多特性，所以更容易写出简洁高效的项目。
