### ISSUE TITLE
[IDEA] 在协程中支持异常

### ISSUE THREAD

**Issue by kedixa** [kedixa/coke#37]
### 使用场景/Where is this idea used
异常是C++错误处理的一部分，让`coke`支持异常可以使其更完备，在业务场景复杂时更好地处理错误。

### 实现思路/How can we implement
https://github.com/kedixa/coke/blob/6534caa1a7213cf46a8d605a9f0b82525cb40080/include/coke/detail/task.h#L184-L193

为`coke::CoPromise`增加一个成员`std::exception_ptr`，在`CoPromise::unhandled_exception`中保存并在`CoPromise::value`时重新抛出即可。如

```cpp
    void unhandled_exception() { eptr = std::current_exception(); }

    T &value() & {
        if (eptr)
            std::rethrow_exception(eptr);
        return result.value();
    }

private:
    std::optional<T> result;
    std::exception_ptr eptr;
```

### 其他信息/Anything else
1. 需要考虑在没有异常抛出的情况下，该改动对整体性能的影响。
2. 并行逻辑下，多个协程都抛出异常如何处理。
3. 如果协程和任务流混合使用，在发生异常时还有待执行的任务，如何定义其行为。
4. 被detach的协程抛出异常时，如何定义其行为。

**Comment by Barenboim** [comment]
更没人看到懂了……

**Comment by kedixa** [comment]
## 支持异常对整体性能的影响
从`Timer`基准测试的`default_timer`（在运行过程中无`coke::Task`参与）和`timer_in_task`（每个timer均运行于`coke::Task`内）对比可以看出，`coke::Task支持异常`这件事本身对性能的影响可以忽略，其差异远小于一个σ。当然这里的测试需要频繁切换线程，σ受各种因素影响，会比较大。

## 无异常分支对性能的影响
`Exception`测试中的`normal_yield`和`yield_catch`对比可以看出，在不发生异常的情况下，增加`try catch`代码块未产生可观测的性能影响。

## 抛出异常对性能的影响
观察`Exception`测试中的其他结果，其中`d`表示协程的嵌套深度，`p`表示异常发生的百分比。

从`dx_p0`测试组可以看出，随着嵌套深度增加，执行耗时有所增加，且感觉远高于普通递归函数的开销，这可能是因为协程调度本身需要一定的开销，且嵌套难以被内联导致的。

从`dx_p100`测试组可以看出，随着嵌套深度增加，执行耗时急剧增加，这表示从深度嵌套的协程内抛出异常会导致很大的开销。与普通函数相比，每一层`coke::Task`处理异常时，都会经历`抛出异常 -> 捕获异常 -> 保存异常 -> 重新抛出异常`的过程，比普通的栈展开复杂很多。

据说目前`libstdc++`使用的异常处理流程会使用全局锁，导致在多线程环境下，异常处理效率很低，该因素需要单独的测试来观察效果，此处与本话题无关，略去。

从`d1_px`测试组可以看出，随着异常比例增加，执行耗时急剧增加，只有异常比例极低（如1%）时（对比`d1_p0`和`d1_p1`），异常对性能的影响才能达到可以接受的程度。

## 其他问题
1. 并行逻辑下，多个协程都可能抛出异常时，建议使用`coke::Future`组件进行处理。目前`coke::sync_wait`与`coke::async_wait`未支持异常处理，有两个想法 1. 增加一个`coke::sync_wait_ex`支持返回异常信息，或者 2. 增加一个`coke::sync_wait_as_future`来支持异常。当然也可以搞一个奇怪的异常组，可以在一个异常里携带所有的异常，不过这也太难用了吧，毕竟未抛异常的部分结果还是需要的。
2. 如果协程和任务流混合使用，若协程抛异常后，仍位于任务流中的任务会继续被调起，但这是一种奇怪的行为，不保证未来会修改该逻辑，因此定义其为`错误行为`。
3. 被detach的协程抛出异常时，暂时定义为`错误行为`，不允许该事件发生。未来可能会模仿被detach的线程抛出异常，这会导致进程经`terminate_handler`退出。

## 结论
1. 支持异常以及无异常分支对性能无可观测影响
2. 频繁的异常对性能影响极大，若确实需要异常来简化逻辑，参考的异常比例为1%

例如，`std::stoi`字符串数值转换系列函数会在无法转换时抛出异常，使用在性能要求高但输入来源不可信的场景下就有一定的问题。
