### ISSUE TITLE
[IDEA] 改进coke::yield性能

### ISSUE THREAD

**Issue by kedixa** [kedixa/coke#39]
### 使用场景/Where is this idea used
`coke::yield`通用场景。

### 实现思路/How can we implement
目前`coke::yield`通过一个时长为0的定时器实现，除了会切换handler线程外，这还会通过`timerfd`额外唤醒一次`poller`线程，这有可能会带来一定的开销。

目前，定时器的取消接口可以直接将任务推送到`handler`队列，可以通过先创建一个有一定时长（如一秒）的定时器，然后立刻取消，来实现一个性能更好的`coke::yield`。

### 其他信息/Anything else
单任务流场景的对比测试

```cpp
#include <iostream>
#include <chrono>

#include "workflow/WFTaskFactory.h"
#include "workflow/WFFacilities.h"

constexpr int N = 100000;

auto now() { return std::chrono::steady_clock::now().time_since_epoch().count(); }

void test(bool flag) {
    WFFacilities::WaitGroup w(1);

    auto rep = [i=0, flag](WFRepeaterTask *) mutable -> SubTask *
    {
        if (i++ < N) {
            if (flag)
                return WFTaskFactory::create_timer_task(0, 0, nullptr);
            else {
                auto *t = WFTaskFactory::create_timer_task("", 1, 0, nullptr);
                WFTaskFactory::cancel_by_name("", 1);
                return t;
            }
        }
        return nullptr;
    };

    auto cb = [&w](WFRepeaterTask *) { w.done(); };
    WFTaskFactory::create_repeater_task(rep, cb)->start();
    w.wait();
}

int main() {
    WFGlobalSettings s = GLOBAL_SETTINGS_DEFAULT;
    s.poller_threads = 2;
    s.handler_threads = 2;
    WORKFLOW_library_init(&s);

    auto start = now();
    test(false);
    auto cost = now() - start;
    std::cout << "Cancel and start, Cost " << cost/1000 << "ms\n";

    start = now();
    test(true);
    cost = now() - start;
    std::cout << "Timer with zero time, Cost " << cost/1000 << "ms\n";

    return 0;
}
```

**Comment by kedixa** [comment]
对比两次`benchmark`结果，改进后的`yield`效果提升到`3998/769≈5.20`倍，有可能是`github action`机器型号在原实现上的效果过于不佳，导致差距极大，本地测试效果提升了约`47%`。

根据该方案和结果，考虑以下问题

1. 该实现在极端情况下是否**更容易**将`handler`队列填满，导致进程死锁
2. `InfiniteDuration`类型的定时器表现不佳，或与该问题相关，考虑做类似调整
3. 目前的`Dag Benchmark`基于`coke::yield`实现，后者改进后对比差异不再有实际意义，应修改对比方式

**Comment by Barenboim** [comment]
目前workflow无法创建一个超时为-1和timer，如果可以的话，你这个性能还会更好。因为-1直接不用查找链表或树了。

**Comment by kedixa** [comment]
> 目前workflow无法创建一个超时为-1的timer，如果可以的话，你这个性能还会更好。因为-1直接不用查找链表或树了。

如果直接支持很不错，而且可以简化实现方式。目前的`yield`实现仍有bug，需要增加一些手法绕过去。

**Comment by kedixa** [comment]
问题一：是，但不绝对。相比于直接向handler队列放入任务，绕行poller线程只是在理论上增大了队列长度，并无本质区别；但可以通过增加poller线程数增大队列长度，只需修改配置重启进程即可，而增大handler队列需要为代码打补丁并重新构建。从最佳实践上讲，构建服务时应当做好资源配置和并发限制，对瞬间请求及时降级，避免压力在请求链上逐级放大，从而避免该问题。
问题二：是，已改进。
问题三：再议。
