### ISSUE TITLE
[IDEA] 等待一组任务，直到其中有k个完成

### ISSUE THREAD

**Issue by kedixa** [kedixa/coke#47]
### 使用场景/Where is this idea used
目标是提供一种机制，可以方便地实现“发起n个任务，当有k个完成（或异常）时发出异步通知”的需求。常见的场景例如，广播一条消息，当有半数以上的服务返回确认消息时视为广播成功。

### 实现思路/How can we implement
`coke`目前对任务的抽象有`WFTask/AwaiterBase`、`coke::Task<T>`以及`coke::Future<T>/coke::Promise<T>`，该机制或应在`coke::Future`这个高级抽象层面实施，其用户接口可以是
```cpp
template<typename T>
Task<int> wait_futures_for(std::vector<Future<T>> &futs, std::size_t k, std::chrono::nanoseconds);
```

或者返回一个新`coke::Future`让用户选择等待多久、等待几次，如
```cpp
template<typename T>
Future<void> wait_futures(std::vector<Future<T>> &futs, std::size_t k);
```

后者虽然灵活，但所有权定义不明，无法表达`futs`在等待结束前不能被外部修改的语义。

**Comment by bugwang** [comment]
就需要这样的功能，找了很多项目基本都不支持这样的功能。这种我看来就是最麻烦的功能。不知道这个项目在生成环境稳定不

**Comment by bugwang** [comment]
多谢分享。相关其他的也一直在关注。目前gcc 12.5.0已经发布 感觉应该可以动手尝试了。如果此项目成熟易用，完全可以取代go了。加油！！！
